### PR TITLE
Allow filter-injectors to take items from HV technic machines

### PR DESCRIPTION
**Pull request by OgelGames**
Allows filter-injectors to take items from the output inventories of HV technic machines.

### CODE REVIEW

**Comment by thomasrudin** [comment]
I tested this on the current server without your modification, this should work out-of-the box. I think those overrides are just there for compat reasons... :/

How did you test that?

**Comment by OgelGames** [comment]
> How did you test that?

I tested it first on the server, where it didn't work for me, and I tested it in my testing world (which has clone of pandorabox-mods) both in singleplayer and as a local server, where it also didn't work (until made the code changes).

I'll try it again on the server, maybe I was just doing something wrong... :thinking:

**Comment by OgelGames** [comment]
Well it works on the server now, don't know why it didn't work yesterday... (Still doesn't work on my testing world though, so maybe there's something wrong with that...)

**Comment by thomasrudin** [comment]
@OgelGames did you use the new all-mod repository:
https://github.com/pandorabox-io/pandorabox-mods/

The mods are an exact match to those on the server...

**Comment by OgelGames** [comment]
> did you use the new all-mod repository:
> https://github.com/pandorabox-io/pandorabox-mods/

Yes (as I mentioned above), but I think it could be something unrelated to the mods, because there seems to be a few other small differences between the server and my testing world...

**Pull request closed without merging**
